config/routes.rb
SampleApp::Application.routes.draw do
resources :users do
  member do
      get :following, :followers
  end
end
resources :books
resources :tv_shows
resources :movies

resources :sessions, only: [:new, :create, :destroy]
resources :microposts, only: [:create, :destroy]

resources :sessions,      only: [:new, :create, :destroy]
resources :microposts,    only: [:create, :destroy]
resources :relationships, only: [:create, :destroy]

root :to => 'static_pages#home'
match '/signup',  to: 'users#new'
match '/signin',  to: 'sessions#new'
match '/signout',  to: 'sessions#destroy'

match '/help', to: 'static_pages#help'
match '/about', to: 'static_pages#about'
match '/contact', to: 'static_pages#contact'
match '/hello1', to: 'books#hello'

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
		@books = Media.find(:all, :conditions => "category_id = 1")
	end

	def show
		@book = Media.find(params[:id])
	end
end

app/helpers/books_helper.rb
module BooksHelper

	def gravatar_for_book(book, options={size: 40})
    gravatar_id = Digest::MD5::hexdigest(book.id.to_s())
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: book.title, class: "gravatar")
	end


end

app/views/books/index.html.erb
<% provide(:title, 'All Books') %> 
<h1>All books</h1>


<ul class="books">
	
	<% @books.each do |book| %>
	<li>
		<%= link_to book.title, book_path(book) %> 
	</li>
	<% end %>
</ul>

app/views/books/show.html.erb
<% provide(:title, @book.title) %> 
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= @book.title %> 
			</h1>
		</section>
	</aside>
</div>